### ISSUE TITLE
Fast-Forward Animation

### ISSUE THREAD

**Issue by LeoWoerteler** [JosuaKrause/BusVis#28]
It should be possible to increase the speed of the current real-time mode, e.g. to one minute per second.

**Comment by JosuaKrause** [comment]
The GUI for the fast forward animation needs a clean-up (improve GUI elements with labels, a secure way to access resources, and lower-case icon filenames)
Also the animation of the radial layout does not work for me while fast-forwarding (it works for the edge based, though).
