### ISSUE TITLE
When already walking, walking again should not be allowed

### ISSUE THREAD

**Issue by JosuaKrause** [JosuaKrause/BusVis#33]
The current walking restriction can be tricked by walking again from another bus station.
At 0:00h from 'Spanierstraße' to 'Klinikum Konstanz' and a maximal walking time of 10min
the routing algorithm returns the following path:

Spanierstraße -> Zähringerplatz (walking, 10min)
Zähringerplatz -> Klinikum Konstanz (walking, 9min)

which contradicts the restriction to 10min walking

**Comment by JosuaKrause** [comment]
I don't know if this is related, but sometimes the routing produces weird results:

At 0:00h from 'Tenbrinkstraße' to 'Am Rheinufer' and a maximal walking time of 5min
the routing algorithm returns the following path:

Tenbrinkstraße -> Markgrafenstraße (walking, 3min)
Markgrafenstraße -> Am Rheinufer (walking, 13min)

the second edge alone is already clearly over 5min

**Comment by LeoWoerteler** [comment]
That's really weird...

**Comment by LeoWoerteler** [comment]
Can't reproduce that:

```
RoutingResult[
  from=Tenbrinkstraße,
  to=Am Rheinufer,
  steps=[
    start at Tenbrinkstraße at 0:00h,
    wait for 12 min,
    take bus line 6 for 1 min to Markgrafenstraße,
    walk 3 min to Am Rheinufer,
  ],
  time=16 min
]
```

**Comment by LeoWoerteler** [comment]
Is it possible that it's a representational issue? The times match, but not the lines:

```
RoutingResult[
  from=Sternenplatz / Spanierstraße,
  to=Klinikum Konstanz,
  steps=[
    start at Sternenplatz / Spanierstraße at 0:00h,
    walk 2 min to Sternenplatz,
    wait for 8 min,
    take bus line 2 for 2 min to Zähringerplatz,
    walk 7 min to Klinikum Konstanz,
  ],
  time=19 min
]
```

**Comment by JosuaKrause** [comment]
The routing and the representation are both correct. Incorrect is only the interpretation of the edge lengths. This cannot be avoided in the current visualization. Opened #35 to handle this.
