### ISSUE TITLE
Better routing

### ISSUE THREAD

**Issue by JosuaKrause** [JosuaKrause/BusVis#88]
Only edges in the interval [t, t + w_e(t)] have to be considered for every edge e, when t is the time when we arrive at a node.

**Comment by LeoWoerteler** [comment]
What is _w_e(t)_?

**Comment by JosuaKrause** [comment]
w_e: R -> R^+_0 is the weight function for an edge e - t is the time.
even for arbitrary weight functions only weights within the interval [t, t+w_e(t)] have to be checked.

**Comment by JosuaKrause** [comment]
Actually the interval is [t, t + w_e(t) + changeTime] to be sure that even changing bus lines does not lead to a better result.
I've implemented this optimization and got an average of 19ms per station on a slow computer (previous was around 150ms)

This lies in the fact that far less routes have to be checked.

```
// old method:
// source: BusStation[Zähringerplatz, 122]
// routes: 627
// queue maxsize: 10433

// new method:
// source: BusStation[Zähringerplatz, 122]
// routes: 204
// queue maxsize: 51
```

As can be seen with those statistics far less routes have to be checked and
the queue does not grow (factor 200) as much (less routes get inserted)

Pull request is coming soon...
